name: New Sentry Release
on:
  push:
    branches:
      - master
jobs:
  createSentryRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create a Sentry.io release
        uses: bjacobel/sentry-cli-action@master
        with:
          args: releases -o solilokiam -p music new ${{ github.sha }}
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
